# Generated by Django 2.2.6 on 2019-11-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CompanyName', models.CharField(max_length=20)),
                ('Employee', models.IntegerField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=30)),
                ('ContactNumber', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('PW', models.CharField(max_length=20)),
            ],
        ),
    ]
