# Generated by Django 2.2.6 on 2019-11-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Employee',
            new_name='EmployeeID',
        ),
    ]
