# Generated by Django 2.2.6 on 2019-11-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_auto_20191113_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('OrderQty', models.IntegerField()),
                ('Material', models.CharField(max_length=100)),
                ('Equipement', models.CharField(max_length=100)),
                ('doc', models.FileField(upload_to='')),
            ],
        ),
    ]
