# Generated by Django 2.2.6 on 2019-11-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_orderproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProName', models.CharField(max_length=50)),
                ('orderdate', models.DateField()),
                ('EmployeeID', models.IntegerField(primary_key=True, serialize=False)),
                ('CustName', models.CharField(max_length=30)),
                ('OrderQty', models.IntegerField()),
                ('Material', models.CharField(max_length=100)),
                ('Equipement', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='orderProduct',
        ),
    ]
