# Generated by Django 2.2.6 on 2019-12-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_product_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='CompanyName',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
