# Generated by Django 2.2.6 on 2019-12-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_product_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='doc',
            field=models.FileField(upload_to='documents'),
        ),
    ]
