# Generated by Django 2.2.6 on 2019-12-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_auto_20191206_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='doc',
            field=models.FileField(upload_to=''),
        ),
    ]
