# Generated by Django 2.2.6 on 2019-12-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_auto_20191206_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='doc',
        ),
    ]
