# Generated by Django 2.2.6 on 2019-11-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeName', models.CharField(max_length=30)),
                ('ContactNo', models.IntegerField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('PW', models.CharField(max_length=15)),
            ],
        ),
    ]
