# Generated by Django 2.2.6 on 2019-11-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeName', models.CharField(max_length=30)),
                ('EmployeeID', models.IntegerField(primary_key=True, serialize=False)),
                ('ContactNo', models.IntegerField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('PW', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='EmpDetails',
        ),
    ]
