# Generated by Django 2.2.6 on 2019-11-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_auto_20191112_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ContactNo',
            field=models.IntegerField(),
        ),
    ]
