# Generated by Django 2.2.6 on 2019-11-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_auto_20191112_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmployeeID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployeeName',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
