# Generated by Django 2.2.6 on 2019-11-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_auto_20191113_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmployeeID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployeeName',
            field=models.CharField(max_length=30),
        ),
    ]
