# Generated by Django 2.2.6 on 2019-11-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_auto_20191113_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production_Testing',
            fields=[
                ('ProductName', models.CharField(max_length=30)),
                ('EmployeeID', models.IntegerField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=30)),
                ('TargetQty', models.IntegerField()),
                ('date', models.DateField()),
                ('RecBorQty', models.IntegerField()),
                ('TestBorQty', models.IntegerField()),
                ('RewBorQty', models.IntegerField()),
                ('ComBorQty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('ProductName', models.CharField(max_length=30)),
                ('EmployeeID', models.IntegerField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=30)),
                ('TargetQty', models.IntegerField()),
                ('date', models.DateField()),
                ('RecBorQty', models.IntegerField()),
                ('TestBorQty', models.IntegerField()),
                ('RewBorQty', models.IntegerField()),
                ('ComBorQty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Soldering',
            fields=[
                ('ProductName', models.CharField(max_length=30)),
                ('EmployeeID', models.IntegerField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=30)),
                ('TargetQty', models.IntegerField()),
                ('RecMatQty', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('ComBorQty', models.IntegerField()),
                ('RewBorQty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('ProductName', models.CharField(max_length=30)),
                ('EmployeeID', models.IntegerField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=30)),
                ('Department', models.CharField(max_length=30)),
                ('MaterialListQty', models.CharField(max_length=1000)),
                ('date', models.DateField()),
            ],
        ),
    ]
