# Generated by Django 2.2.6 on 2019-11-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_auto_20191128_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production_testing',
            name='TestBorQty',
            field=models.IntegerField(),
        ),
    ]
